### ISSUE TITLE
Client-Side Exception Occurs on Logout

### ISSUE THREAD

**Issue by Kushhhhhhhh** [TusharSoni014/stablemax#1]
Hello, 

I encountered an error when attempting to log out of the application. The error message displayed was:
"Application error: a client-side exception has occurred (see the browser console for more information)."

This issue appears each time I click on the logout button. 
Could you please look into it and provide a fix? 
Let me know if any additional information is needed to help debug. 

Thank you!
![Screenshot (41)](https://github.com/user-attachments/assets/37724c70-4ad2-426e-903c-7eec27e8e6ac)

**Comment by TusharSoni014** [comment]
Hii, thanks for finding this issue, i know why its happening.

When the user logs out, 401 error is thrown and the page dont loads, it can be easily fixed by logout redirection or middleware,

will take a look
